#!/bin/sh

. $TS_GLOBAL

PT=`dirname $0`
cd $PT

./arp-fix

killall psi_gen
killall psi0
killall psi1
killall psi2
killall dvbserver
killall encserver
killall net_cam_client.sh
killall net_cam_client
killall userver

sleep 2

if [ -e /root/manual_devserver_run ] ; then
    . /root/manual_devserver_run
else 

    if [ -e /dvbserver/bin/services.conf ] ; then
	./dvbserver
    fi

    if [ -e /dvbserver/bin/encoders.conf ] ; then
	./encserver
    fi
    ./net_cam_client.sh "$NET_CAM_CLIENT_VERSION" "$NET_CAM_CLIENT_PARAMS"&

fi
